package generator

const matrixTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>JFrog CLI — PM Compatibility</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #0A0A0A;
    color: #F0F0F0;
    font-size: 13px;
    line-height: 1.5;
  }
  header { padding: 28px 40px 20px; border-bottom: 1px solid #1E1E1E; }
  header h1 { font-size: 20px; font-weight: 700; letter-spacing: -.01em; margin-bottom: 10px; }
  header h1 span { color: #40BE46; }
  .meta { font-size: 12px; color: #606060; display: flex; gap: 24px; flex-wrap: wrap; }
  .meta .stat { display: flex; align-items: center; gap: 6px; }
  .stat-dot { width: 7px; height: 7px; border-radius: 50%; }
  .dot-passing { background: #40BE46; }
  .dot-failing  { background: #E84B3A; }
  .dot-pending  { background: #F5A623; }
  main { padding: 24px 40px 48px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  thead th {
    text-align: left; padding: 0 12px 10px;
    font-size: 10px; font-weight: 700; text-transform: uppercase;
    letter-spacing: .1em; color: #606060; border-bottom: 1px solid #1E1E1E;
  }
  tbody tr { border-bottom: 1px solid #141414; }
  tbody tr:hover { background: #111111; }
  tbody td { padding: 8px 12px; color: #A0A0A0; }
  td.version { font-family: 'JetBrains Mono', 'Fira Code', monospace; color: #E0E0E0; }
  td.type { font-size: 11px; }
  .status-passing { color: #40BE46; font-weight: 600; }
  .status-failing  { color: #E84B3A; font-weight: 600; }
  .status-pending  { color: #F5A623; font-weight: 600; }
  .status-unknown  { color: #606060; }
  a { color: #40BE46; text-decoration: none; }
  a:hover { text-decoration: underline; }
  .pm-group-row td {
    padding: 16px 12px 6px; font-size: 11px; font-weight: 700;
    text-transform: uppercase; letter-spacing: .1em;
    color: #404040; border-bottom: 1px solid #1E1E1E;
  }
  footer { padding: 20px 40px; border-top: 1px solid #1E1E1E; font-size: 11px; color: #404040; }
</style>
</head>
<body>
<header>
  <h1>JFrog CLI — <span>Package Manager Compatibility</span></h1>
  <div class="meta">
    <span class="stat"><span class="stat-dot dot-passing"></span>{{.Passing}} passing</span>
    <span class="stat"><span class="stat-dot dot-failing"></span>{{.Failing}} failing</span>
    <span class="stat"><span class="stat-dot dot-pending"></span>{{.Pending}} pending</span>
    <span>{{.Total}} versions tracked</span>
    <span>Updated {{.GeneratedAt}}</span>
  </div>
</header>
<main>
  <table>
    <thead>
      <tr>
        <th>Package Manager</th>
        <th>Version</th>
        <th>Type</th>
        <th>Status</th>
        <th>Tested Against</th>
        <th>Date</th>
        <th>Run</th>
      </tr>
    </thead>
    <tbody>
      {{range .Groups}}
      <tr class="pm-group-row"><td colspan="7">{{.Name}}</td></tr>
      {{range .Versions}}
      <tr>
        <td></td>
        <td class="version">{{.Version}}</td>
        <td class="type">{{.Type}}</td>
        <td class="{{.StatusClass}}">{{.Status}}</td>
        <td>{{if .JFCLIVersion}}jfrog-cli {{.JFCLIVersion}}{{else}}—{{end}}</td>
        <td>{{if .Date}}{{.Date}}{{else}}—{{end}}</td>
        <td>{{if .RunURL}}<a href="{{.RunURL}}" target="_blank">View</a>{{else}}—{{end}}</td>
      </tr>
      {{end}}
      {{end}}
    </tbody>
  </table>
</main>
<footer>
  Auto-generated by <a href="https://github.com/agrasth/pm-version-monitor">pm-version-monitor</a>
  &middot; Updated on every test run
</footer>
</body>
</html>`
